### ISSUE TITLE
Neo4J Instance crashes and doesn't come back up

### ISSUE THREAD

**Issue by snowzach** [ncats/stitcher#146]
We have been querying the public neo4j instance and it appears to occasionally crash and doesn't comes back up.

**Comment by southalln** [comment]
I believe that service doesn't benefit from an auto-restart script at the moment.
Moreover, I think this behavior is actually yet another symptom of the out of memory we are getting from #145 using filter=stauts/Latest

**Comment by southalln** [comment]
@caodac is is possible to confirm out of memory for the neo4j?

**Comment by caodac** [comment]
yeah, the instance hosting it isn't very big. it should be back now. we'll add this to our monitor.

**Comment by snowzach** [comment]
Thanks
